extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern u8 bob_dl_zoo_iceban_side_ci4[];
extern u8 bob_dl_zoo_iceban_side_ci4_pal_rgba16[];
extern u8 bob_dl_m05_snw0_i8[];
extern Vtx bob_dl_IceIslandVisual_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_IceIslandVisual_mesh_layer_1_vtx_0[46];
extern Gfx bob_dl_IceIslandVisual_mesh_layer_1_tri_0[];
extern Vtx bob_dl_IceIslandVisual_mesh_layer_1_vtx_1[135];
extern Gfx bob_dl_IceIslandVisual_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Tower_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Tower_mesh_layer_1_vtx_0[67];
extern Gfx bob_dl_Tower_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Tower_mesh_layer_1_vtx_1[32];
extern Gfx bob_dl_Tower_mesh_layer_1_tri_1[];
extern Gfx mat_bob_dl_ice_wall_001_layer1_area1[];
extern Gfx mat_revert_bob_dl_ice_wall_001_layer1_area1[];
extern Gfx mat_bob_dl_snow_001_layer1_area1[];
extern Gfx mat_revert_bob_dl_snow_001_layer1_area1[];
extern Gfx bob_dl_IceIslandVisual_mesh_layer_1[];
extern Gfx bob_dl_Tower_mesh_layer_1[];
extern Gfx bob_dl_material_revert_render_settings[];
